export const REQUEST_SEARCH_RESULTS = 'REQUEST_SEARCH_RESULTS';
export const RECIEVE_SEARCH_RESULTS = 'RECIEVE_SEARCH_RESULTS';

export const REQUEST_TITLE_DATA = 'REQUEST_TITLE_DATA';
export const RECIEVE_TITLE_DATA = 'RECIEVE_TITLE_DATA';
