export const REQUEST_SEARCH_RESULTS = 'REQUEST_SEARCH_RESULTS';
export const RECIEVE_SEARCH_RESULTS = 'RECIEVE_SEARCH_RESULTS';

export const REQUEST_TITLE_DATA = 'REQUEST_TITLE_DATA';
export const RECIEVE_TITLE_DATA = 'RECIEVE_TITLE_DATA';

export const REQUEST_CURRENT_MOVIES = 'REQUEST_CURRENT_MOVIES';
export const RECIEVE_CURRENT_MOVIES = 'RECIEVE_CURRENT_MOVIES';

export const REQUEST_BEST_MOVIES = 'REQUEST_BEST_MOVIES';
export const RECIEVE_BEST_MOVIES = 'RECIEVE_BEST_MOVIES';
